# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install NodeJS
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install resume-cli
        run: npm install -g resume-cli

      - name: Install npm dependencies
        run: npm install

      - name: Compile CSS
        run: npm run build:styles:3

      - name: Build HTML
        run: resume export output/index.html --theme=.

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'bahuma-me'
          server: 'server4.bahuma.io'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './output/*'
          remote_path: '/var/www/vhosts/bahuma.io/httpdocs/www'
          args: '-o ConnectTimeout=5'
